# Generated by Django 5.2.5 on 2025-09-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('order_confirmed', 'Order Confirmed'), ('order_in_progress', 'Order In Progress'), ('order_completed', 'Order Completed'), ('order_cancelled', 'Order Cancelled'), ('order_paid', 'Order Payment Received'), ('payment_success', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('order_message', 'New Order Message'), ('order_file', 'New Order File'), ('review_received', 'New Review Received'), ('service_featured', 'Service Featured'), ('system', 'System Notification')], max_length=20),
        ),
    ]
