# Generated by Django 5.2.5 on 2025-09-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleranalytics',
            name='pending_orders',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='selleranalytics',
            name='in_progress_orders',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
