# Generated by Django 5.2.5 on 2025-08-18 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_order_notification_orderfile_ordermessage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('business_description', models.TextField(blank=True)),
                ('business_website', models.URLField(blank=True)),
                ('business_phone', models.CharField(blank=True, max_length=20)),
                ('business_address', models.TextField(blank=True)),
                ('skills', models.JSONField(blank=True, default=list, help_text='List of skills/expertise')),
                ('experience_years', models.PositiveIntegerField(default=0, help_text='Years of experience')),
                ('education', models.TextField(blank=True)),
                ('certifications', models.JSONField(blank=True, default=list, help_text='List of certifications')),
                ('portfolio_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('behance_url', models.URLField(blank=True)),
                ('response_time', models.PositiveIntegerField(default=24, help_text='Average response time in hours')),
                ('completion_rate', models.DecimalField(decimal_places=2, default=100.0, help_text='Order completion rate percentage', max_digits=5)),
                ('on_time_delivery_rate', models.DecimalField(decimal_places=2, default=100.0, help_text='On-time delivery rate percentage', max_digits=5)),
                ('is_available', models.BooleanField(default=True, help_text='Whether seller is accepting new orders')),
                ('max_orders_per_month', models.PositiveIntegerField(default=10, help_text='Maximum orders per month')),
                ('current_month_orders', models.PositiveIntegerField(default=0, help_text='Current month orders')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seller Profile',
                'verbose_name_plural': 'Seller Profiles',
            },
        ),
        migrations.CreateModel(
            name='SellerAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_services', models.PositiveIntegerField(default=0)),
                ('active_services', models.PositiveIntegerField(default=0)),
                ('featured_services', models.PositiveIntegerField(default=0)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('completed_orders', models.PositiveIntegerField(default=0)),
                ('cancelled_orders', models.PositiveIntegerField(default=0)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('five_star_reviews', models.PositiveIntegerField(default=0)),
                ('four_star_reviews', models.PositiveIntegerField(default=0)),
                ('three_star_reviews', models.PositiveIntegerField(default=0)),
                ('two_star_reviews', models.PositiveIntegerField(default=0)),
                ('one_star_reviews', models.PositiveIntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_platform_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('paid_out_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pending_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('orders_this_month', models.PositiveIntegerField(default=0)),
                ('earnings_this_month', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('orders_this_year', models.PositiveIntegerField(default=0)),
                ('earnings_this_year', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Seller Analytics',
                'unique_together': {('seller',)},
            },
        ),
        migrations.CreateModel(
            name='SellerEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, help_text='Total order amount', max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, help_text='Platform commission', max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Amount after platform fee', max_digits=10)),
                ('is_paid_out', models.BooleanField(default=False, help_text='Whether earnings have been paid out')),
                ('paid_out_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='services.order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('seller', 'order')},
            },
        ),
    ]
