# Generated by Django 5.2.5 on 2025-08-18 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_sellerprofile_selleranalytics_sellerearnings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('company_size', models.CharField(blank=True, help_text='e.g., 1-10, 11-50, 51-200, 200+', max_length=50)),
                ('preferred_categories', models.JSONField(blank=True, default=list, help_text='List of preferred service categories')),
                ('budget_range', models.CharField(blank=True, help_text='e.g., $100-500, $500-1000, $1000+', max_length=50)),
                ('preferred_delivery_time', models.CharField(blank=True, help_text='e.g., 1-3 days, 1 week, 2 weeks+', max_length=50)),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('platform', 'Platform Messages')], default='email', max_length=20)),
                ('notification_preferences', models.JSONField(blank=True, default=dict, help_text='Notification settings')),
                ('is_active', models.BooleanField(default=True)),
                ('auto_save_services', models.BooleanField(default=True, help_text='Automatically save viewed services')),
                ('show_recommendations', models.BooleanField(default=True, help_text='Show personalized recommendations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Buyer Profile',
                'verbose_name_plural': 'Buyer Profiles',
            },
        ),
        migrations.CreateModel(
            name='BuyerAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('completed_orders', models.PositiveIntegerField(default=0)),
                ('cancelled_orders', models.PositiveIntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_reviews_given', models.PositiveIntegerField(default=0)),
                ('average_rating_given', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_services_viewed', models.PositiveIntegerField(default=0)),
                ('total_services_saved', models.PositiveIntegerField(default=0)),
                ('favorite_categories', models.JSONField(blank=True, default=list, help_text='Most viewed/saved categories')),
                ('orders_this_month', models.PositiveIntegerField(default=0)),
                ('spent_this_month', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('orders_this_year', models.PositiveIntegerField(default=0)),
                ('spent_this_year', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('last_order_date', models.DateTimeField(blank=True, null=True)),
                ('last_review_date', models.DateTimeField(blank=True, null=True)),
                ('last_login_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Buyer Analytics',
                'unique_together': {('buyer',)},
            },
        ),
        migrations.CreateModel(
            name='BuyerPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_service_types', models.JSONField(blank=True, default=list, help_text='Types of services preferred')),
                ('preferred_seller_level', models.CharField(choices=[('any', 'Any Level'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='any', max_length=20)),
                ('preferred_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum seller rating preferred', max_digits=3)),
                ('min_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preferred_currency', models.CharField(default='USD', max_length=3)),
                ('language_preference', models.CharField(default='en', help_text='Preferred language for communication', max_length=10)),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('response_time_preference', models.PositiveIntegerField(default=24, help_text='Preferred seller response time in hours')),
                ('email_notifications', models.BooleanField(default=True)),
                ('order_updates', models.BooleanField(default=True)),
                ('new_services', models.BooleanField(default=True)),
                ('recommendations', models.BooleanField(default=True)),
                ('marketing_emails', models.BooleanField(default=False)),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('sellers_only', 'Sellers Only')], default='public', max_length=20)),
                ('show_order_history', models.BooleanField(default=True)),
                ('show_reviews', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Buyer Preferences',
                'unique_together': {('buyer',)},
            },
        ),
        migrations.CreateModel(
            name='SavedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Personal notes about the service')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_services', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='services.service')),
            ],
            options={
                'ordering': ['-saved_at'],
                'unique_together': {('buyer', 'service')},
            },
        ),
    ]
